//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int Id { get; set; }
        public string Record { get; set; }
        public string Complaints { get; set; }
        public string Absence { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Vendor_Name { get; set; }
        public Nullable<int> Id_Client { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
