//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date_order { get; set; }
        public string Medicine { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Vendor_Name { get; set; }
        public Nullable<int> Id_Client { get; set; }
        public Nullable<double> Unit_Price { get; set; }
        public Nullable<double> Order_Cost { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
